/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "DISCOURSE_SSO_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ELASTICSEARCH_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ELASTICSEARCH_NODE": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MyVpc": {
      "type": "sst.aws.Vpc"
    }
    "STYTCH_PROJECT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "STYTCH_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ServiceNestJS": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
    "SyncGbif": {
      "assignPublicIp": boolean
      "cluster": string
      "containers": any
      "securityGroups": any
      "subnets": any
      "taskDefinition": string
      "type": "sst.aws.Task"
    }
    "SyncPx": {
      "assignPublicIp": boolean
      "cluster": string
      "containers": any
      "securityGroups": any
      "subnets": any
      "taskDefinition": string
      "type": "sst.aws.Task"
    }
    "SyncVd": {
      "assignPublicIp": boolean
      "cluster": string
      "containers": any
      "securityGroups": any
      "subnets": any
      "taskDefinition": string
      "type": "sst.aws.Task"
    }
    "SyncVdData": {
      "assignPublicIp": boolean
      "cluster": string
      "containers": any
      "securityGroups": any
      "subnets": any
      "taskDefinition": string
      "type": "sst.aws.Task"
    }
    "SyncVt": {
      "assignPublicIp": boolean
      "cluster": string
      "containers": any
      "securityGroups": any
      "subnets": any
      "taskDefinition": string
      "type": "sst.aws.Task"
    }
    "SyncVtData": {
      "assignPublicIp": boolean
      "cluster": string
      "containers": any
      "securityGroups": any
      "subnets": any
      "taskDefinition": string
      "type": "sst.aws.Task"
    }
    "Web": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}